#spring:
#  profiles:
#    active: dev
#  application:
#    name: music-service
#  config:
#    import: "optional:configserver:"

server:
  port: 7040
  data:
    neo4j:
      uri: bolt://localhost:7687
      authentication:
        username: neo4j
        password: secret@1234


